### ISSUE TITLE
Still using deprecated rollup option key

### ISSUE THREAD

**Issue by guilhermehn** [jlmakes/karma-rollup-preprocessor#24]
The `entry`key should be changed to `input` since rollup@0.48. Setting the rollup dependency version to `>=0.45.x` making new installations to get the 0.48.x versions, thus causing breaking changes.
https://github.com/jlmakes/karma-rollup-preprocessor/blob/56f48f7500acd147d88108166481de61d7c36308/lib/index.js#L37

**Comment by jlmakes** [comment]
Still running into issues unfortunately.

**Comment by jlmakes** [comment]
Still running into some issues…

**Comment by mjeanroy** [comment]
@jlmakes What kind of issues? I just checked the `master` branch on one of my project and it seems good.

**Comment by jlmakes** [comment]
- ❌ Rollup 0.48.2 / Legacy Config / Preprocessor `4.0.3`
  > `Unexpected key 'moduleName' found`

- ❌ Rollup 0.48.2 / Legacy Config / Preprocessor `master`
  > `Unexpected key 'moduleName' found`

- ❌ Rollup 0.48.2 / New Config / Preprocessor `4.0.3`
  > `options.entry is deprecated, use options.input`

- ✅ Rollup 0.48.2 / New Config / preprocessor `master`


Contrary to Rich Harris’ tweet suggesting there shouldn’t be much breakage—this doesn’t look very backwards compatible.

I’m wondering if preprocessor 4.x should be legacy format (i.e. `rollup < 0.48.0`)
and a new preprocessor 5.x would support the new format (i.e. `rollup >= 0.48.0`)

Thoughts?

**Comment by mjeanroy** [comment]
Your errors seems related to the configuration in your project since the preprocessor does not set/get any `moduleName` option.

I don't think this is the responsibility of the `karma-rollup-preprocessor` to patch the configuration to the new (or old format) for keys that are not read or set by the preprocessor. Instead each project should use a rollup configuration which is compatible with the version of rollup installed in the project, but maybe I'm wrong.

> The complete abandon of semantic versioning for Rollup is frustrating

Well... Until a version 1.0.0 is released, semantic versioning [allow breaking changes](http://semver.org/#spec-item-4) between versions. But that's frustrating, I agree :)

**Comment by jlmakes** [comment]
So, if developers run into errors or warnings because the preprocessor installed a different version of Rollup—it’s up to the developer to update their configuration… not the preprocessor to continue to work with their existing configuration?

**Comment by mjeanroy** [comment]
@jlmakes Maybe, rollup should be a peer dependencies, not a direct dependencies?

Doing this will force developers to choose what version of rollup to install, and so use a configuration compatible with the version that is installed (for example, karma-webpack define webpack as a [peer dependency](https://github.com/webpack-contrib/karma-webpack/blob/v2.0.4/package.json#L34) too). That said, doing this will be a breaking change.

**Comment by jlmakes** [comment]
I’m not sure I see a path that doesn’t involve a breaking change in the preprocessor... and that sounds better than managing what version of Rollup is installed.

So what about preprocessor 4.0.4 with `0.45 <= rollup < 0.48` to damage control broken legacy configuration objects (since v4 does manage rollup dep version)...

And a preprocessor 5.0.0 that doesn’t manage dep version with with peer `rollup >= 0.45`

**Comment by mjeanroy** [comment]
> So what about a preprocessor bump to 4.0.4 with 0.45 <= rollup < 0.48 to damage control broken legacy configs... and a preprocessor 5.0.0 with peer rollup >= 0.48?

That seems good 👌
