### ISSUE TITLE
Watcher should only recompile changed files, and its dependents.

### ISSUE THREAD

**Issue by Paulskit** [jlmakes/karma-rollup-preprocessor#28]
Default behavior for karma is to trigger processing only on changed file. This is very fast and convenient if you debug tests in watch mode. 
Current implementation forces all files to be processed on any file change. Consequently, it takes a lot of time on large tests amount just to check 1 file change. 

Just an example:
1) Default karma file watch + rollup
30 08 2017 15:18:36.617:INFO [watcher]: Changed file "./test/unit/behavior/noResultsBehavior.spec.js".
30 08 2017 15:18:36.791:INFO [watcher]: Changed file "./test/unit/behavior/noResultsBehavior.spec.js".
Less than 200ms to recompile and trigger test run.

2) Current implementation with custom watcher:
75 seconds to respond to single file change. (66 files and 564 tests recompiled in total)

**Comment by jlmakes** [comment]
_Figure 1:_

**Submodules:** A, B
**Modules:** 1, 2, 3, 4
**Tests:** T1, T2
![Example Dependency Tree](https://user-images.githubusercontent.com/2044842/29876061-0858d44e-8d9c-11e7-9cfa-1d65f742c7fd.jpg)
Karma’s default behavior ignores dependent modules… so if **B** changes, _only_ B will be reprocessed… and everything downstream that depends on B will now be stale. This is what #3 is about, and what #11 improved in version 3.

So, the custom watcher _should_ take more time, because it’s processing more files. Our goal is to ensure the updated file—and its dependent downstream—are processed again. Ideally, we'd recompile only the changed file, and its descendants… so if **B** changes, then **1, 3, T1,** and **T2** are recompiled.

_Figure 2:_
![Example Dependency Tree](https://user-images.githubusercontent.com/2044842/29879405-415df176-8da5-11e7-9c87-3e21faa1a6f9.jpg)

This is exactly what version 3 does, except that it unintentionally re-ran tests for each processed file (#17). That means in the example above, the tests would have ran 5 times after changing **B**. Aside from spamming your terminal, Karma would encounter errors and false negatives.

So… `karma-rollup-preprocessor@5.0.x` addresses #3 and #17 with a new watcher that simply reprocesses all files; there’s definitely room for improvement, potentially using a strategy similar to #11 with the new watcher.

I’ll take a look at making this improvement for `v5.1`

**Comment by Paulskit** [comment]
While I completely agree with your info graphics, I'm not sure what I see locally corresponds to what you're saying. Saving a single .spec.js file with no external dependencies (no imports, requires, etc) now triggers full rebuild of all files with rollup.
Running all tests is not an issue, you can always limit only desired set of tests using something like 'fdescribe'. 
Let me see if I could create a demo project for this.

**Comment by Paulskit** [comment]
Ok, here we go: https://github.com/Paulskit/rollup-karma-performance-bug
Steps to reproduce:
1) npm i
2) npm test
3) Save translate.js or translate.spec.js

As you can see, on every translate file change (which has no external dependencies) you see warnings in console about not used dependencies. Those are coming from mock1 file specifically for this reason. It proofs that despite the file doesn't have any external dependencies, entire bundle recompilation is triggered.

**Comment by jlmakes** [comment]
I appreciate the reproduction; I don’t think I was clear before, so allow me be blunt…

**The current behavior is by design.**

I will say again: you’re not wrong, and I agree it has room for improvement—but the simple fact is that there are constraints when integrating with Karma, and the current file watcher is the first one that:

- Correctly recompiles dependencies
- Does not excessively re-run tests
- Throw errors and false negatives

The cost is performance, and I will look at improving it for `v5.1`

**Comment by Paulskit** [comment]
Clear enough. Thank you.

**Comment by danielnaab** [comment]
For anyone encountering this, here's my solution: create a test manifest that explicitly imports every spec in your test suite, and put only that single entry-point in the Karma config.

Watch tasks are much faster, due to the single compilation.

Presumably this is something that could be automated as part of the preprocessor, but is easy enough to maintain as an additional module in the test suite itself.

**Comment by jlmakes** [comment]
Cool workaround Daniel!
