### ISSUE TITLE
Karma not watching preprocessed files?

### ISSUE THREAD

**Issue by CrowdHailer** [jlmakes/karma-rollup-preprocessor#3]
When using this plugin and trying to watch my test files with karma, only changing the entry file causes the test files to be recompiled.

I have tried explicitly watching the rest of the test files but even though doing this causes the tests to run again, the test file is not recompiled! 😅

<details>
<summary>My Karma Config</summary>

```js
// Karma configuration
// Generated on Mon Dec 14 2015 17:29:26 GMT+0000 (GMT)

module.exports = function(config) {
  config.set({

    // base path that will be used to resolve all patterns (eg. files, exclude)
    basePath: '',


    // frameworks to use
    // available frameworks: https://npmjs.org/browse/keyword/karma-adapter
    frameworks: ['jasmine'],


    // list of files / patterns to load in the browser
    files: [
      'test/client-test.js',
      {pattern: 'test/*', watched: true, included: false, served: false, nocache: false}
    ],


    // list of files to exclude
    exclude: [
    ],


    // preprocess matching files before serving them to the browser
    // available preprocessors: https://npmjs.org/browse/keyword/karma-preprocessor
    preprocessors: {
      'test/client-test.js': ['rollup']
    },


    // test results reporter to use
    // possible values: 'dots', 'progress'
    // available reporters: https://npmjs.org/browse/keyword/karma-reporter
    reporters: ['progress'],


    // web server port
    port: 9876,


    // enable / disable colors in the output (reporters and logs)
    colors: true,


    // level of logging
    // possible values: config.LOG_DISABLE || config.LOG_ERROR || config.LOG_WARN || config.LOG_INFO || config.LOG_DEBUG
    logLevel: config.LOG_INFO,


    // enable / disable watching file and executing tests whenever any file changes
    autoWatch: true,


    // start these browsers
    // available browser launchers: https://npmjs.org/browse/keyword/karma-launcher
    browsers: ['Firefox'],


    // Continuous Integration mode
    // if true, Karma captures browsers, runs the tests and exits
    singleRun: false,

    // Concurrency level
    // how many browser should be started simultanous
    concurrency: Infinity
  })
}
```
</details>

**Comment by klaascuvelier** [comment]
I have the feeling this is more of a configuration issue rather than an issue with the pre-processor. But I'll look into it asap.

**Comment by ccampbell** [comment]
I am running into this same issue. When I have karma set to watch my test directory then any change to a test file cause it to be rebuilt with the rollup preprocessor, but changes to the src files imported by the test files are never recompiled. I have to manually kill and restart karma each time I change a src file which is very frustrating.

Any ideas on how to fix this?

**Comment by mjeanroy** [comment]
Same behavior here. When test file is updated, rollup preprocessor does its job perfectly, otherwise when an src file is updated, rollup preprocessor does not run at all (it seems to not be executed by karma).

@ccampbell A quick workaround, instead of restarting karma, is to save your test file again to force rollup preprocessor to do its magic again.

**Comment by ccampbell** [comment]
@mjeanroy in my experience, that only works to recompile the test code and not the src code. 

What I have found is that if my karma config is referencing `{pattern: 'test/*-test.js'}` in the `files` section then saving a src file does nothing, but a test file will rebuild the files in the test directory.

If my karma config is referencing `{patten: 'test/specificfile-test.js'}` in the `files` section then saving a src file does nothing, but a test file will rebuild both the files in the test directory as well as the files in the src directory. So I have been using that when I want to have the tests run as I'm changing src code, but it is a bit annoying.

**Comment by brianmhunt** [comment]
This problem is picky.  Here's [a SO post I made on it](http://stackoverflow.com/q/37795680/19212) as I've tried several workarounds.

**Comment by brianmhunt** [comment]
I have created [a repository for demonstrating](https://github.com/brianmhunt/karma-rollup-preprocessor-issue-3) the issue.

**Comment by jlmakes** [comment]
I believe I've wrapped my head around the problem, thanks to @brianmhunt and [his work](https://github.com/jlmakes/karma-rollup-preprocessor/pull/11).

If we were to assume we had 2 files:
```js
// foo.js
export { data: 'bar' }
```

```js
// foo.spec.js
import foo from './foo.js';

expect(foo).to.be.defined;
```

We would end up with a new temporary file served to the Karma browser, something like this:

```js
// foo.spec.bundle.js
var foo = { data: 'bar' };

expect(foo).to.be.defined;
```

Rollup simply imports the contents of the files it finds in the `import` statement at the time of bundling. So when we change...

```diff
// foo.js
- export { data: 'bar' }
+ export { data: 'wunderbar' }
```

Karma will re-run our tests because we've set it up to watch all our files, but because `foo.spec.js` hasn't changed, our test bundle is still the same:

```js
// foo.spec.bundle.js
var foo = { data: 'bar' };

expect(foo).to.be.defined;
```

But if we update `foo.spec.js`:

```js
// foo.spec.js
import foo from './foo.js';

expect(foo).to.be.defined;
expect(foo.data).to.equal('wunderbar');
```

It will trigger Rollup to re-bundle that file, and it will grab `foo.js` again (which has changed since the last time it bundled) and we'll get:

```js
// foo.spec.bundle.js
var foo = { data: 'wunderbar' };

expect(foo).to.be.defined;
expect(foo.data).to.equal('wunderbar');
```

The reason @brianmhunt's PR solves this problem, is because it forces all bundles to be recompiled (by manually changing the modified and accessed times) when any of the files they `import` change.

So in our above example, when `foo.js` was changed, it would change the accessed and modified times of `foo.spec.js`, triggering Karma's watch handler to rebundle `foo.spec.bundle.js` 🎉

The only caveat seems to be that the solution relies on debouncing, so that saving a file doesn't trigger multiple re-runs of the test suite. It's certainly better than having broke file watching, but I'm exploring improvements.

Either way, there _will_ be a release that includes this fix in the next 1-3 days.
