### ISSUE TITLE
Not compatible with the latest version of Rollup (v1.0.0)

### ISSUE THREAD

**Issue by fengyuanchen** [jlmakes/karma-rollup-preprocessor#42]
The Rollup@1.0.0 had been released yesterday, when I upgrade to the latest version, I got the following error:

```js
TypeError: Cannot read property 'forEach' of undefined
at Watch.capture (~\node_modules\karma-rollup-preprocessor\lib\index.js:65:20)
at rollup.then.bundle (~\node_modules\karma-rollup-preprocessor\lib\index.js:21:23)
```

> It seems that the `bundle.modules` had been moved to `bundle.cache.modules`.

**Comment by jlmakes** [comment]
Thanks @fengyuanchen, I'm on it.

**Comment by jlmakes** [comment]
📣 **Status Update**: The next release is right around the corner (on or before Monday, 1/14).

Since this is a major release (dropping support for Rollup < 1 and Node < 8), I'm also doing what I can to improve the file watcher (re: #28) — I've been getting _very_ friendly with the Karma source, and I've got a strong lead on a solution.

@isidrok @tatey @niksy @thisconnect @givanse
@calebdwilliams @ckbo3hrk @pantosha @MartijnR
